pipeline{
    agent any

    stages{
        stage("Compile Stage"){
            steps{
                withMaven(maven: 'm3'){
                    sh 'mvn clean compile'
                }                
            }
        }
        stage("Test Stage"){
            steps{
                withMaven(maven: 'm3'){
                    sh 'mvn test'
                }                
            }
        }
        stage("Final Stage"){
            steps{
                withMaven(maven: 'm3'){
                    sh 'mvn install'
                }                
            }
        }        
    }
}